// Static image map for activity icons — black and white variants.
// React Native requires static require() calls, so each path must be explicit.

const black = {
  run: require('../../assets/images/activities/black/corrida.png'),
  trail_run: require('../../assets/images/activities/black/trail.png'),
  stroll: require('../../assets/images/activities/black/passeio.png'),
  walk: require('../../assets/images/activities/black/caminhada.png'),
  wheelchair: require('../../assets/images/activities/black/cadeira-de-rodas.png'),
  cycle: require('../../assets/images/activities/black/ciclismo.png'),
  ebike: require('../../assets/images/activities/black/bicicleta-eletrica.png'),
  mtb: require('../../assets/images/activities/black/btt.png'),
  weight_training: require('../../assets/images/activities/black/treino-com-pesos.png'),
  workout: require('../../assets/images/activities/black/treino.png'),
  hiit: require('../../assets/images/activities/black/hiit.png'),
  crossfit: require('../../assets/images/activities/black/crossfit.png'),
  physiotherapy: require('../../assets/images/activities/black/fisioterapia.png'),
  tennis: require('../../assets/images/activities/black/tenis.png'),
  padel: require('../../assets/images/activities/black/padel.png'),
  squash: require('../../assets/images/activities/black/squash.png'),
  badminton: require('../../assets/images/activities/black/badminton.png'),
  table_tennis: require('../../assets/images/activities/black/tenis-de-mesa.png'),
  swimming: require('../../assets/images/activities/black/natacao.png'),
  surf: require('../../assets/images/activities/black/surf.png'),
  stand_up_paddle: require('../../assets/images/activities/black/sup.png'),
  kayak: require('../../assets/images/activities/black/caiaque.png'),
  rowing: require('../../assets/images/activities/black/remo.png'),
  canoeing: require('../../assets/images/activities/black/canoagem.png'),
  sailing: require('../../assets/images/activities/black/vela.png'),
  ice_skating: require('../../assets/images/activities/black/patinagem-no-gelo.png'),
  snowboard: require('../../assets/images/activities/black/snowboard.png'),
  alpine_skiing: require('../../assets/images/activities/black/esqui-alpino.png'),
  football: require('../../assets/images/activities/black/futebol.png'),
  basketball: require('../../assets/images/activities/black/basquetebol.png'),
  volleyball: require('../../assets/images/activities/black/voleibol.png'),
  futsal: require('../../assets/images/activities/black/futsal.png'),
  yoga: require('../../assets/images/activities/black/ioga.png'),
  dance: require('../../assets/images/activities/black/danca.png'),
  skateboard: require('../../assets/images/activities/black/skate.png'),
  pilates: require('../../assets/images/activities/black/pilates.png'),
} as const;

const white = {
  run: require('../../assets/images/activities/white/corrida.png'),
  trail_run: require('../../assets/images/activities/white/trail.png'),
  stroll: require('../../assets/images/activities/white/passeio.png'),
  walk: require('../../assets/images/activities/white/caminhada.png'),
  wheelchair: require('../../assets/images/activities/white/cadeira-de-rodas.png'),
  cycle: require('../../assets/images/activities/white/ciclismo.png'),
  ebike: require('../../assets/images/activities/white/bicicleta-eletrica.png'),
  mtb: require('../../assets/images/activities/white/btt.png'),
  weight_training: require('../../assets/images/activities/white/treino-com-pesos.png'),
  workout: require('../../assets/images/activities/white/treino.png'),
  hiit: require('../../assets/images/activities/white/hiit.png'),
  crossfit: require('../../assets/images/activities/white/crossfit.png'),
  physiotherapy: require('../../assets/images/activities/white/fisioterapia.png'),
  tennis: require('../../assets/images/activities/white/tenis.png'),
  padel: require('../../assets/images/activities/white/padel.png'),
  squash: require('../../assets/images/activities/white/squash.png'),
  badminton: require('../../assets/images/activities/white/badminton.png'),
  table_tennis: require('../../assets/images/activities/white/tenis-de-mesa.png'),
  swimming: require('../../assets/images/activities/white/natacao.png'),
  surf: require('../../assets/images/activities/white/surf.png'),
  stand_up_paddle: require('../../assets/images/activities/white/sup.png'),
  kayak: require('../../assets/images/activities/white/caiaque.png'),
  rowing: require('../../assets/images/activities/white/remo.png'),
  canoeing: require('../../assets/images/activities/white/canoagem.png'),
  sailing: require('../../assets/images/activities/white/vela.png'),
  ice_skating: require('../../assets/images/activities/white/patinagem-no-gelo.png'),
  snowboard: require('../../assets/images/activities/white/snowboard.png'),
  alpine_skiing: require('../../assets/images/activities/white/esqui-alpino.png'),
  football: require('../../assets/images/activities/white/futebol.png'),
  basketball: require('../../assets/images/activities/white/basquetebol.png'),
  volleyball: require('../../assets/images/activities/white/voleibol.png'),
  futsal: require('../../assets/images/activities/white/futsal.png'),
  yoga: require('../../assets/images/activities/white/ioga.png'),
  dance: require('../../assets/images/activities/white/danca.png'),
  skateboard: require('../../assets/images/activities/white/skate.png'),
  pilates: require('../../assets/images/activities/white/pilates.png'),
} as const;

const ACTIVITY_IMAGES = { black, white } as const;

export function getActivityImage(key: string, variant: 'black' | 'white'): any {
  return (ACTIVITY_IMAGES[variant] as Record<string, any>)[key] ?? null;
}
